### ISSUE TITLE
Doesn't seem to do anything

### ISSUE THREAD

**Issue by Camaroni** [AlexIII/lwf#1]
Hello! 

I just purchased the app and downloaded it, as I need this mini PC to be able to make a local network hotspot when there is no internet available. I'm running the app as administrator, and it doesn't seem to be doing anything.

**Comment by AlexIII** [comment]
Hi!
What do you mean you "purchased the app"? It's free (and comes with no guarantee).

In order for this app to work you need to be sure that your wifi adapter supports Access Point mode. The app does not checks that.
You can try setup the AP manually via cmd (as admin), run

```
netsh wlan set hostednetwork mode=allow ssid=MY_NEW_NETWORK key=12345678
netsh wlan start hostednetwork
```

After that, you should be able to see an error message If something in the system prevents you from hosting an AP.

If the net starts successfully, you can stop it by running
```
netsh wlan stop hostednetwork
```

**Comment by Camaroni** [comment]
Ahh, darn. I was hoping this would be a magical way around the hosted network not being supported by the wifi adapter. I purchased the app via the windows store, which makes me wonder if it was posted there by some third party

**Comment by AlexIII** [comment]
>  I purchased the app via the windows store, which makes me wonder if it was posted there by some third party

It most certainly was. It's not illegal, though. I suggest you ask for refund or support there.

**Comment by Camaroni** [comment]
Currently doing that now. Thank you! I'll see if I can't find some USB wifi adapter that will support a hosted network

**Comment by AlexIII** [comment]
If it's ok to ask, could you share a link to the page where you purchased the app? I couldn't find it myself.
