### ISSUE TITLE
DHCP?

### ISSUE THREAD

**Issue by r3a1d3a1** [AlexIII/lwf#2]
How can it work w/o a DHCP server? 
I'm trying to get it to with the help of a separate DHCP server and it still fails.

**Comment by AlexIII** [comment]
Hi!
This app is just a small gui over the standad windows `netsh` command. It just runs `netsh wlan set hostednetwork mode=allow ssid=XXXXX key=XXXXX`, so you need to find out how to make DHCP work with `netsh`.
